name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required for creating releases
    
    steps:
    - name: Determine tag
      id: tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.tag.outputs.tag }}
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # Match the go.mod requirement
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build Linux binary
      run: go build -o mcp_proxy_linux ./main.go
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        files: mcp_proxy_linux
        body: |
          ## Release ${{ steps.tag.outputs.tag }}
          
          ### Changes
          - Built for Linux (x86_64)
          
          ### Installation
          Download the `mcp_proxy_linux` binary and make it executable:
          ```bash
          chmod +x mcp_proxy_linux
          ./mcp_proxy_linux
          ```
          
          ### Requirements
          - Linux x86_64 system
          - Environment variables for configuration (see SERVER.md)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}